// Ordered: active statuses first, then service changes, then removals/closures
export const TANK_STATUS_LABELS = {
  TAC: 'Active',
  TTC: 'Temporarily Closed',
  TOS: 'Temporarily Out of Service',
  TCP: 'Closed In Place',
  TCS: 'Change In Service',
  TRR: 'Removed and Replaced',
  TRM: 'Removed Tank Verified',
  TR8: 'Removed Prior to 1988',
  TER: 'Removed Tank Ereg',
  TBL: 'Removed Tank Backlog Regs',
  T96: 'Removed Tank 1996 Regs',
  TAB: 'Abandoned',
  TRA: 'Abandoned Tank Newly Discovered',
  TUR: 'Removed Tank Unverified',
  TEX: 'Exempt',
  TNF: 'Not Found',
  TNV: 'Not Verified',
  TNR: 'Not Registered',
  CAR: 'Contract Application Received',
  DEF: 'Diesel Exhaust Fluid Tank',
  DUP: 'Duplicate Tank',
  NFA: 'No Further Action',
  TPS: 'Pending Sotra',
};
